### ISSUE TITLE
The data has a leading 0.

### ISSUE THREAD

**Issue by DaLiangLee** [eastbanctechru/right-angled#100]
https://github.com/angular/angular/issues/23079#event-1554424395

Looking forward to your reply.

**Comment by fshchudlo** [comment]
Hello.
If I correctly understand the problem, you need to set [coerce](https://eastbanctechru.github.io/right-angled-demo/filters#coerce) flag to `false` for your filter settings and everything will be ok.

**Comment by DaLiangLee** [comment]
Thank you very much. My question is solved.
