### ISSUE TITLE
A problem arises when transforming a table into an expandable table. I think I can also select the inner tr, but it seems that it can't be realized. Is there a solution to this problem?

### ISSUE THREAD

**Issue by DaLiangLee** [eastbanctechru/right-angled#101]
What I expect is to click the row to select the current row. Click on the inner table to select the current row.

Looking forward to your reply, thank you
![1](https://user-images.githubusercontent.com/21189061/46798758-6bef7600-cd85-11e8-86e3-6119746efced.gif)

**Comment by DaLiangLee** [comment]
![martin_2018-10-11_18-44-34](https://user-images.githubusercontent.com/21189061/46798862-b7098900-cd85-11e8-8010-9c35a38f4daa.png)
The outer table selects the current line. I did this.

**Comment by fshchudlo** [comment]
Hello.
There's not enough information for me to understand what can be wrong.
Can you, please, build a demo on [stackblitz](https://stackblitz.com/) or at least provide templates of your tables?

**Comment by DaLiangLee** [comment]
`<div style="z-index: 50; padding-top:220px; width: 100%"  class="table-responsive hideGrid" [class.hideGrid]="noRecord">
        <table class="table table-striped" [rtList]="getOrders" #list="rtList" >
            <tbody  style="position: relative;" rtSelectionArea  [multiple]="multiple">
                <ng-template ngFor let-order [ngForOf]="list.items" let-i="index">
                    <tr (click)="onselectedDeliveryRows($event,order,i)">
                        <td (click)="expandOrder($event,order)" style="cursor:pointer" >
                            <i [ngClass]="{'fa': true, 'fa-caret-right': !order.expanded,'fa-caret-down': order.expanded, 'fa-lg': true}"></i>
                        </td>
                        <td>
                            <input type="checkbox" [hidden]="order.isQtyMismatch" [(ngModel)]="order.selected" [rtSelectionCheckboxFor]="order" [(selected)]="order.selected" style="cursor:pointer;" (change)="onCheckBoxChange()" [hidden]="order.exception == null">
                        </td>
                        <td>{{order.phase}}</td>
                        <td>{{order.saP_DeliveryOrderId}}</td>
                        <td>{{order.deliveryDateTime| date:'MM/dd/yyyy hh:mm a'}}</td>
                        <td>{{order.customer}}</td>
                        <td>{{order.shipTo}}</td>
                        <td>{{order.soNumber}}</td>
                        <td>{{order.carrier}}</td>
                        <td>{{order.currentOwnerDepartmentCode}}</td>
                        <td class="redText" [hidden]="!order.orderIsQueueManaged">{{order.exception}}</td>
                        <td [hidden]="!order.orderIsQueueManaged">
                            <input type="button" class='btn btn-success btn-sm' [hidden]="order.dwsExceptionId == 0" value='Manage' (click)='handleException(order.dwsExceptionId,order.currentOwnerDepartmentCode,order.correctiveAction)'>
                        </td>
                    </tr>
                    <tr [hidden]='!order.expanded'>
                        <td style="background:#fff"></td>
                        <td style="background:#fff"></td>
                        <td colspan="10" style="padding:0px">
                            <table class="table table-striped"  style="margin-bottom: 0px;">
                                <tbody style="position: relative;">
                                    <ng-template ngFor let-line [ngForOf]="order.lineItems" let-i="index">
                                        <tr>
                                            <td>
                                                <input type="checkbox" [(ngModel)]="line.selected" [rtSelectionCheckboxFor]="line" [(selected)]="line.selected" style="cursor:pointer;" (change)="onCheckBoxChange()" [hidden]="line.exception == null || line.hasClosed">
                                            </td>
                                            <td>{{line.line}}</td>
                                            <td>{{line.materialID}}</td>
                                            <td>{{line.description}}</td>
                                            <td class="rightjustified">{{line.orderQty | number:'1.3'}}</td>
                                            <td class="rightjustified">{{line.pickedQty | number:'1.3'}}</td>
                                            <td class="rightjustified">{{line.remainingQty | number:'1.3'}}</td>
                                            <td>{{line.uoM}}</td>
                                            <td [hidden]="line.hasClosed">{{line.deliveryPhaseCode}}</td>
                                            <td [hidden]="line.hasClosed">{{line.department}}</td>
                                            <td [hidden]="line.hasClosed || !order.orderDetailIsQueueManaged" class="redText">{{line.exception}}</td>
                                            <td>
                                                <input type="button" class='btn btn-success btn-sm' [hidden]="line.dwsExceptionId == 0 || line.hasClosed || !order.orderDetailIsQueueManaged" value='Manage' (click)='handleException(line.dwsExceptionId,line.currentOwnerDepartmentCode,line.correctiveAction)'>
                                            </td>
                                        </tr>
                                    </ng-template>
                                    <tr style="text-align:center;" *ngIf="!order.lineItems || order.lineItems.length === 0">
                                        <td colspan="12">No submission record found.</td>
                                    </tr>
                                </tbody>
                                <thead>
                                    <tr>
                                        
                                        <th style="width:5%"></th>
                                        <th style="width:5%"><span>Line</span></th>
                                        <th style="width:10%"><span>Material</span></th>
                                        <th style="width:12%"><span>Description</span></th>
                                        <th style="width:8%" class="rightjustified"><span>Delivery Qty</span></th>
                                        <th style="width:8%" class="rightjustified"><span>Picked Qty</span></th>
                                        <th style="width:8%" class="rightjustified"><span>Remaining Qty</span></th>
                                        <th style="width:6%"><span>UoM</span></th>
                                        <th style="width:8%"><span>Exception Phase</span></th>
                                        <th style="width:5%"><span>Department</span></th>
                                        <th style="width:10%"><span>Exception</span></th>
                                        <th style="width:15%"><span>Action</span></th>
                                    </tr>
                                </thead>
                            </table>
                        </td>
                    </tr>
                </ng-template>
            </tbody>
            <thead>
                <tr>
                    <th style="position: relative; width:4% " [style.top]="columnTop"><span></span>
                    </th>
                    <th style="position: relative; width:4% " [style.top]="columnTop"><span></span>
                    </th>
                    <th style="position: relative; width:8% "  [style.top]="columnTop"><span>Phase</span>
                    </th>
                    <th style="position: relative; width:8% " [style.top]="columnTop"><span rtSort="del_order">Delivery</span>
                    </th>
                    <th style="position: relative; width:12% " [style.top]="columnTop"><span rtSort="requested_delivery">Delivery Date/Time</span>
                    </th>
                    <th style="position: relative; width:10% " [style.top]="columnTop"><span rtSort="customer">Customer</span>
                    </th>
                    <th style="position: relative; width:8% " [style.top]="columnTop"><span rtSort="shipto">Ship To</span>
                    </th>
                    <th style="position: relative; width:8% " [style.top]="columnTop"><span rtSort="so_number">SO Number</span>
                    </th>
                    <th style="position: relative; width:8% " [style.top]="columnTop"><span rtSort="carrier">Truck</span>
                    </th>
                    <th style="position: relative; width:10% " [style.top]="columnTop"><span>Department</span>
                    </th>
                    <th style="position: relative; width:10% " [style.top]="columnTop"><span>Exception</span>
                    </th>
                    <th style="position: relative; width:10% " [style.top]="columnTop"><span>Action</span>
                    </th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td colspan="13">
                        <rt-status-progress>
                            <progress-bar></progress-bar>
                        </rt-status-progress>
                        <rt-status-no-data class="text-center">
                            0 records found
                        </rt-status-no-data>
                        <div>
                            <rt-status-done>
                                <rt-buffered-pager [defaultRowCount]="20" #rtPager>
                                    <span>{{rtPager.pager.loadedCount}} record{{rtPager.pager.loadedCount > 1 ? 's' : ''}} found
                                    </span>
                                    <a *ngIf="rtPager.canLoadMore" tabindex="0" (click)="rtPager.loadMore()" rtPreventDefaults="click" [class.hidden]="!rtPager.canLoadMore"
                                        [rtInfinite]="window" href="#">Show more</a>
                                </rt-buffered-pager>
                            </rt-status-done>
                        </div>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>`
`
  onselectedDeliveryRows(event: any, order: any, index: any) {
    console.log(index);
    if (event.target.type === 'checkbox' || order.exception == null) {
      return;
    }
    // console.log(order);
    const selectElement = this.selectionArea.selectionService;
    console.log(selectElement);
    selectElement.toggleSelection(index, true);
    this.changeFooterBtnStatus();
  }`

Thank you very much for your reply. I first provided the code for the table and tried to implement my code in stackblitz. My requirement is that clicking on the line (including the tr of the secondary table) can also be selected, and then do some operations.

**Comment by DaLiangLee** [comment]
Sorry, the code is very messy, I will sort it out for you.

table

`<div style="z-index: 50; padding-top:220px; width: 100%"  class="table-responsive hideGrid" [class.hideGrid]="noRecord">
        <table class="table table-striped" [rtList]="getOrders" #list="rtList" >
            <tbody  style="position: relative;" rtSelectionArea  [multiple]="multiple">
                <ng-template ngFor let-order [ngForOf]="list.items" let-i="index">
                    <tr (click)="onselectedDeliveryRows($event,order,i)">
                        <td (click)="expandOrder($event,order)" style="cursor:pointer" >
                            <i [ngClass]="{'fa': true, 'fa-caret-right': !order.expanded,'fa-caret-down': order.expanded, 'fa-lg': true}"></i>
                        </td>
                        <td>
                            <input type="checkbox" [hidden]="order.isQtyMismatch" [(ngModel)]="order.selected" [rtSelectionCheckboxFor]="order" [(selected)]="order.selected" style="cursor:pointer;" (change)="onCheckBoxChange()" [hidden]="order.exception == null">
                        </td>
                        <td>{{order.phase}}</td>
                        <td>{{order.saP_DeliveryOrderId}}</td>
                        <td>{{order.deliveryDateTime| date:'MM/dd/yyyy hh:mm a'}}</td>
                        <td>{{order.customer}}</td>
                        <td>{{order.shipTo}}</td>
                        <td>{{order.soNumber}}</td>
                        <td>{{order.carrier}}</td>
                        <td>{{order.currentOwnerDepartmentCode}}</td>
                        <td class="redText" [hidden]="!order.orderIsQueueManaged">{{order.exception}}</td>
                        <td [hidden]="!order.orderIsQueueManaged">
                            <input type="button" class='btn btn-success btn-sm' [hidden]="order.dwsExceptionId == 0" value='Manage' (click)='handleException(order.dwsExceptionId,order.currentOwnerDepartmentCode,order.correctiveAction)'>
                        </td>
                    </tr>
                    <tr [hidden]='!order.expanded'>
                        <td style="background:#fff"></td>
                        <td style="background:#fff"></td>
                        <td colspan="10" style="padding:0px">
                            <table class="table table-striped"  style="margin-bottom: 0px;">
                                <tbody style="position: relative;">
                                    <ng-template ngFor let-line [ngForOf]="order.lineItems" let-i="index">
                                        <tr>
                                            <td>
                                                <input type="checkbox" [(ngModel)]="line.selected" [rtSelectionCheckboxFor]="line" [(selected)]="line.selected" style="cursor:pointer;" (change)="onCheckBoxChange()" [hidden]="line.exception == null || line.hasClosed">
                                            </td>
                                            <td>{{line.line}}</td>
                                            <td>{{line.materialID}}</td>
                                            <td>{{line.description}}</td>
                                            <td class="rightjustified">{{line.orderQty | number:'1.3'}}</td>
                                            <td class="rightjustified">{{line.pickedQty | number:'1.3'}}</td>
                                            <td class="rightjustified">{{line.remainingQty | number:'1.3'}}</td>
                                            <td>{{line.uoM}}</td>
                                            <td [hidden]="line.hasClosed">{{line.deliveryPhaseCode}}</td>
                                            <td [hidden]="line.hasClosed">{{line.department}}</td>
                                            <td [hidden]="line.hasClosed || !order.orderDetailIsQueueManaged" class="redText">{{line.exception}}</td>
                                            <td>
                                                <input type="button" class='btn btn-success btn-sm' [hidden]="line.dwsExceptionId == 0 || line.hasClosed || !order.orderDetailIsQueueManaged" value='Manage' (click)='handleException(line.dwsExceptionId,line.currentOwnerDepartmentCode,line.correctiveAction)'>
                                            </td>
                                        </tr>
                                    </ng-template>
                                    <tr style="text-align:center;" *ngIf="!order.lineItems || order.lineItems.length === 0">
                                        <td colspan="12">No submission record found.</td>
                                    </tr>
                                </tbody>
                                <thead>
                                    <tr>
                                        
                                        <th style="width:5%"></th>
                                        <th style="width:5%"><span>Line</span></th>
                                        <th style="width:10%"><span>Material</span></th>
                                        <th style="width:12%"><span>Description</span></th>
                                        <th style="width:8%" class="rightjustified"><span>Delivery Qty</span></th>
                                        <th style="width:8%" class="rightjustified"><span>Picked Qty</span></th>
                                        <th style="width:8%" class="rightjustified"><span>Remaining Qty</span></th>
                                        <th style="width:6%"><span>UoM</span></th>
                                        <th style="width:8%"><span>Exception Phase</span></th>
                                        <th style="width:5%"><span>Department</span></th>
                                        <th style="width:10%"><span>Exception</span></th>
                                        <th style="width:15%"><span>Action</span></th>
                                    </tr>
                                </thead>
                            </table>
                        </td>
                    </tr>
                </ng-template>
            </tbody>
            <thead>
                <tr>
                    <th style="position: relative; width:4% " [style.top]="columnTop"><span></span>
                    </th>
                    <th style="position: relative; width:4% " [style.top]="columnTop"><span></span>
                    </th>
                    <th style="position: relative; width:8% "  [style.top]="columnTop"><span>Phase</span>
                    </th>
                    <th style="position: relative; width:8% " [style.top]="columnTop"><span rtSort="del_order">Delivery</span>
                    </th>
                    <th style="position: relative; width:12% " [style.top]="columnTop"><span rtSort="requested_delivery">Delivery Date/Time</span>
                    </th>
                    <th style="position: relative; width:10% " [style.top]="columnTop"><span rtSort="customer">Customer</span>
                    </th>
                    <th style="position: relative; width:8% " [style.top]="columnTop"><span rtSort="shipto">Ship To</span>
                    </th>
                    <th style="position: relative; width:8% " [style.top]="columnTop"><span rtSort="so_number">SO Number</span>
                    </th>
                    <th style="position: relative; width:8% " [style.top]="columnTop"><span rtSort="carrier">Truck</span>
                    </th>
                    <th style="position: relative; width:10% " [style.top]="columnTop"><span>Department</span>
                    </th>
                    <th style="position: relative; width:10% " [style.top]="columnTop"><span>Exception</span>
                    </th>
                    <th style="position: relative; width:10% " [style.top]="columnTop"><span>Action</span>
                    </th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td colspan="13">
                        <rt-status-progress>
                            <progress-bar></progress-bar>
                        </rt-status-progress>
                        <rt-status-no-data class="text-center">
                            0 records found
                        </rt-status-no-data>
                        <div>
                            <rt-status-done>
                                <rt-buffered-pager [defaultRowCount]="20" #rtPager>
                                    <span>{{rtPager.pager.loadedCount}} record{{rtPager.pager.loadedCount > 1 ? 's' : ''}} found
                                    </span>
                                    <a *ngIf="rtPager.canLoadMore" tabindex="0" (click)="rtPager.loadMore()" rtPreventDefaults="click" [class.hidden]="!rtPager.canLoadMore"
                                        [rtInfinite]="window" href="#">Show more</a>
                                </rt-buffered-pager>
                            </rt-status-done>
                        </div>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
`

**Comment by DaLiangLee** [comment]
`
  onselectedDeliveryRows(event: any, order: any, index: any) {
    console.log(index);
    if (event.target.type === 'checkbox' || order.exception == null) {
      return;
    }
    // console.log(order);
    const selectElement = this.selectionArea.selectionService;
    console.log(selectElement);
    selectElement.toggleSelection(index, true);
    this.changeFooterBtnStatus();
  }
`
This is the method I wrote by clicking tr to select the current line.

**Comment by DaLiangLee** [comment]
God, why does the code look unformatted, sorry, I won't use it...

**Comment by fshchudlo** [comment]
Sorry for late response.
Without reproduction I can't be sure what's going on. But I see that you have nested collections and use `rtSelectionCheckboxFor` for all of them.
In this case you need to use `rtSelectionArea` for each level of hierarchy.
Simply put `rtSelectionArea` directive to nested `tbody`.

**Comment by DaLiangLee** [comment]
Thank you very much for your reply, 
but in this case click on the tr line will be invalid.
`onselectedDeliveryRows(event: any, order: any, index: any) {
    console.log(order);
    
    if (event.target.type === 'checkbox' || order.exception == null) {
      return;
    }
    const selectElement = this.selectionArea.selectionService;
    selectElement.toggleSelection(index, true);
    this.changeFooterBtnStatus();
  }`

**Comment by DaLiangLee** [comment]
Thank you very much, I have seen this directive, The selection through the check box is correct, if you can choose by clicking tr, it is better.
Right-angled is very powerful and very easy to use!!!
