### ISSUE TITLE
I think it would be perfect if I could ‘Lock header’ for table.

### ISSUE THREAD

**Issue by DaLiangLee** [eastbanctechru/right-angled#102]
https://eastbanctechru.github.io/right-angled-demo/paging-and-statuses#buffered-pager

Additional buffered pager directives

**Comment by fshchudlo** [comment]
Hello.
Can you please explain in more details the problem and desired behaviour? 
From current description I totally don't understand what you need.

**Comment by DaLiangLee** [comment]
Thank you very much for your reply.
I want table lock header.

**Comment by DaLiangLee** [comment]
![1](https://user-images.githubusercontent.com/21189061/48595682-c2f1f780-e990-11e8-859f-6811ff4f874a.gif)
like this

**Comment by fshchudlo** [comment]
This behaviour can be achieved with css styles.
There's nothing to implement in right-angled since it's main idea is to be free of any predefined css
