### ISSUE TITLE
 Virtual scroll support

### ISSUE THREAD

**Issue by denismaster** [eastbanctechru/right-angled#104]
It would be great to support virtual scrolling in right angled.

Currently we have an option for infinite scrolling. In that case we can load more data when we scroll content to the end. Howewer, what if we have a really big amount of data, for example, 1M rows ? In that case html dom will die really fast. And virtual scroll solve this issue with rendering only small amount of data, that is only visible on screen. 

Popular implementations, such as ngx-datatable, use precalculation of each row height, because each row can have different height, and then calculate overall table content height.  Than it use scrollbar position to calculate which records must be drawn on the screen and which records should be eliminated from dom.

**Comment by fshchudlo** [comment]
Hello.
Sorry for so late response. For some reason I didn't get notification about your issue.
I've tried to use `right-angled` with [Angular CDK Virtual Scroll](https://material.angular.io/cdk/scrolling/overview#virtual-scrolling) component and they play well together.
Live demo is available [here](https://eastbanctechru.github.io/right-angled/paging-and-statuses#virtual-scroll).
