### ISSUE TITLE
Can't install lib to project

### ISSUE THREAD

**Issue by denismaster** [eastbanctechru/right-angled#80]
Hello! I'm trying to add right-angled to project. I run `npm install --save right-angled` in console.
Then I done all things presente in quick tour, such as importing a module and adding them to the import section of my module.

But when I'm running the projects, there is one error:

> Unexpected value 'RTModule' imported by the module 'RouteModule'

Is there any workaround? Or  am I doing something wrong maybe?

**Comment by fshchudlo** [comment]
Hello.
I get exact same error when trying to install `right-angled` to the project with different version of `angular`. I can't find any ways to fix this problem in the `right-angled` library. So, the only way I see is to use same version of `angular` (currently is 2.2.0)  in your project.

**Comment by denismaster** [comment]
Thank you very much, I've deleted the `node_modules/right-angled/node_modules/@angular` and it works!
Right-angled are awesome!
