### ISSUE TITLE
how to prevent rtList from blinking

### ISSUE THREAD

**Issue by GerrAlt12** [eastbanctechru/right-angled#85]
Hello!

Each time when I call loadData() rtList emptify loaded list, wait for new one from server and render it. This bihavior have one disadvantage: if user scroll list down and perform, for example, edit, after this action list will be reloaded, and (because of emptification of list) re-rendered as scrolled top. In addition when list eptified and re-rendered user get blink at UI.

Can I re-render list without emptification of old one?

**Comment by fshchudlo** [comment]
Hello.
You can see the current solution [here in demo application](https://eastbanctechru.github.io/right-angled-demo/list-controls#custom-items-handling)

**Comment by fshchudlo** [comment]
I added new option to the `right-angled` library which addresses your issue in more elegant way. You can see details [here](https://eastbanctechru.github.io/right-angled-demo/list-controls#keep-records-on-load)
