### ISSUE TITLE
Provide way to do some actions, when list is successfully loaded.

### ISSUE THREAD

**Issue by denismaster** [eastbanctechru/right-angled#94]
Hello. I think it is a good idea to provide a way to perform some actions, call callbacks, when list is successfully loaded.

Today, there is a loadSuccessCallback already defined in RtList. We can decorate it with callbackDecorator, such as:
```
export function callbackDecorator(func: Function, callback: any) {
    if (!callback || typeof (callback) !== "function")
        return undefined;
    return function () {
        let result = func.apply(this, arguments);
        callback();
        return result;
    }
}
...
this.list.loadSuccessCallback = callbackDecorator(this.list.loadSuccessCallback, callback);
```
But what about a better way? what about a `afterListLoaded`, similar to `afterListInit`, or returning a `Promise/Observable` from` loadData()` ?

**Comment by fshchudlo** [comment]
Hello.
It's quite easy to implement such feature. But I'm not sure that I understand your use case correctly. 
Particullary, why not perform any success or failure logic in method with which your fetch your data?
I mean something like this:

```javascript
export class UseListComponent {
  constructor(private airportsService: AirportsService) {
  }
  getAirports = (request: AirportsListRequest): Observable<Airport[]> => {
        return this.airportsService.getAirportsList(request)
          .do(
            (response) => console.log('success'),
            (err) => console.log('error')
          );
  }
}
```
Please, provide more details about your use case, If I misunderstand something and such approach is not good for you.

**Comment by denismaster** [comment]
In my application I use custom pagination component, and i need to update it's settings when the list is ready. In this component I can access to RtPager instanse and perform loading actions with it properties and methods.

**Comment by fshchudlo** [comment]
Done.
Now `loadData` an `reloadData` methods of `RTList` and all related components will return result of `fetchMethod`. As described in docs, it can be `Observable`, `Promise` or `EventEmitter`.
If you try to implement some generic control and you need to handle all kinds of subscriptions, you can use `AsyncSubscriber` class to handle subscriptions in abstract manner [like in `List` class](https://github.com/eastbanctechru/e2e4/blob/master/src/list.ts)
