### ISSUE TITLE
Enhancement: emptyIfNullOrUndefined serializeFormatter 

### ISSUE THREAD

**Issue by Romanchuk** [eastbanctechru/right-angled#96]
Is it possible to implement default serializeFormatter that would set parameter value equals to empty string if original value is null or undefined?

```
let emptyIfNullOrUndefined = function(value: any) {
  return value == null ? '' : value;
};

export class RequestListFilter {
  @filter(<FilterConfig>{ serializeFormatter: emptyIfNullOrUndefined }) public date: Date = null;
  @filter(<FilterConfig>{ serializeFormatter: emptyIfNullOrUndefined }) public periodDateFrom: Date = null;
  @filter(<FilterConfig>{ serializeFormatter: emptyIfNullOrUndefined }) public periodDateTo: Date = null;
  @filter(<FilterConfig>{ serializeFormatter: emptyIfNullOrUndefined }) public businessProcess: string = null;
  @filter(<FilterConfig>{ serializeFormatter: emptyIfNullOrUndefined }) public requester: string = null;
  @filter() public statuses: string[] = [];
}
```

**Comment by fshchudlo** [comment]
Now you can use [omitIfNullOrUndefined](https://eastbanctechru.github.io/e2e4/interfaces/filterconfig.html#omitifnullorundefined) config property to exclude `null` and `undefined` values from request. By default this option is disabled, but you can change it globally with [DefaultFilterConfig](https://eastbanctechru.github.io/e2e4/index.html#defaultfilterconfig)
