### ISSUE TITLE
An issue with a request parameter 'take' after reset

### ISSUE THREAD

**Issue by r-kundal** [eastbanctechru/right-angled#98]
It seems there is a problem with a pager when user resets a filter.

Steps to reproduce using a demo ([https://eastbanctechru.github.io/right-angled-demo/filters](url)):
1. Filter by field and do search clicking by Load data:

> Request json: { "skip": 0, "take": 5, "airportName": null, "country": "marsh", "airportSize": null, "airportType": null, "sortings": [] }

2. Click Reset settings
3. Click Load data again

> Request json: { "skip": 0, "take": 1, "airportName": null, "country": null, "airportSize": null, "airportType": null, "sortings": [] }

So, a take parameter have value 1 mistakenly but should 5.

**Comment by fshchudlo** [comment]
Fixed in [version 1.2.1](https://github.com/eastbanctechru/right-angled/releases/tag/v1.2.1)
